// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyjHhEWsoHPD_3Ef-sG71ZdbNkYpEm3q0',
    appId: '1:75381408693:web:3c915030c8df44ab51cffc',
    messagingSenderId: '75381408693',
    projectId: 'greenmed-d6902',
    authDomain: 'greenmed-d6902.firebaseapp.com',
    storageBucket: 'greenmed-d6902.firebasestorage.app',
    measurementId: 'G-L42FSXZR67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJBN-1oPCzHvH5DqNxE5mNwiZYDMyl0c',
    appId: '1:75381408693:android:ed0f8dad3d28f71c51cffc',
    messagingSenderId: '75381408693',
    projectId: 'greenmed-d6902',
    storageBucket: 'greenmed-d6902.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkRADvuqAmxTfkGb-03ZuVnNEoO7dISjM',
    appId: '1:75381408693:ios:b36a94cc1503a3bc51cffc',
    messagingSenderId: '75381408693',
    projectId: 'greenmed-d6902',
    storageBucket: 'greenmed-d6902.firebasestorage.app',
    androidClientId: '75381408693-og448t4fk8pr5uh5k9b3btp2ojak203m.apps.googleusercontent.com',
    iosClientId: '75381408693-p8m4olni5ddc1rqht8hlerlq10hbb50n.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenmedDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDftBV8Soj4k8P4vibtO5vePy6FM3QIsTY',
    appId: '1:97792142793:ios:49b7623d14a2a8a11ecc18',
    messagingSenderId: '97792142793',
    projectId: 'skiive',
    storageBucket: 'skiive.appspot.com',
    androidClientId: '97792142793-61uganonf3q1cl6iert9ugqq3854banc.apps.googleusercontent.com',
    iosClientId: '97792142793-vnn5tes2iu2ob89ahrp5in1l2729tgsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.skiive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyjHhEWsoHPD_3Ef-sG71ZdbNkYpEm3q0',
    appId: '1:75381408693:web:f676877feebb403251cffc',
    messagingSenderId: '75381408693',
    projectId: 'greenmed-d6902',
    authDomain: 'greenmed-d6902.firebaseapp.com',
    storageBucket: 'greenmed-d6902.firebasestorage.app',
    measurementId: 'G-2PRPK4TQN6',
  );

}